name: bitcoin

owner: bitcoin
repo: bitcoin

language: Cpp
ccs:
- dergoegge

engines:
- LibFuzzer
- AflPlusPlus
- HonggFuzz
- None
sanitizers:
- Address
- Undefined
- Memory
- Coverage
- CmpLog
- ValueProfile
- None

architecture: X86_64

fuzz_env_var: FUZZ

cpu_hours_per_campaign: 48
report_repo: "dergoegge/fuzzor-reports"
